{% set name = "dkist" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dkist-{{ version }}.tar.gz
  sha256: 147791ced81db8147e46ecb4f48db9e7d4f1bb98e290aabc36e468228cebb248

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=30.3.0
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.9
    - asdf >=3.3.0
    - asdf-astropy >=0.5.0
    - asdf-coordinates-schemas >=0.3.0
    - asdf-standard >=1.1.0
    - asdf-transform-schemas >=0.6.0
    - asdf-wcs-schemas >=0.4.0
    - astropy-base >=6.0
    - dask-core >=2023.2.0
    - globus-sdk >=3.0
    - gwcs >=0.24.0
    - matplotlib-base >=3.7
    - ndcube >=2.1
    - reproject >=0.7.1 # ndcube reproject extra
    - numpy >=1.25
    - parfive >=2.2
    - platformdirs >=3.0
    - sunpy >=5.0.7
    - tqdm  >=4.65

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-doctestplus
    - pytest-remotedata
    - pytest-mock
    - pytest-mpl
    - pytest-httpserver
    - pytest-benchmark
    - pytest-lazy-fixtures
    - hypothesis
  imports:
    - dkist
  commands:
    - pip check  - this is failing due to a pyavm (reproject dep)
    - pytest --pyargs dkist -k "not test_fail" --remote-data=none -m "not mpl_image_compare"

about:
  home: http://dkist.nso.edu
  summary: DKIST User Tools
  license: BSD-3-Clause
  license_file: LICENSE.rst
  dev_url: https://github.com/DKISTDC/dkist

extra:
  recipe-maintainers:
    - Cadair
    - SolarDrew
